### ISSUE TITLE
Add OpenBLAS 0.2.19 package

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-math#1]
@xianyi released [OpenBLAS 0.2.19](https://github.com/xianyi/OpenBLAS/releases/tag/v0.2.19) on 1-Sep-2016. Should add a new CK package.

Ideally, it should reuse the [installation script](https://github.com/ctuning/ck-math/blob/master/package/lib-openblas-0.2.18/install.sh) from the OpenBLAS 0.2.18 package, rather than copy and modify it. (It has some AArch64 changes coming.) For an example, see [CK-Caffe](https://github.com/dividiti/ck-caffe) where the GPU versions (e.g. [lib-caffe-bvlc-master-cuda](https://github.com/dividiti/ck-caffe/tree/master/package/lib-caffe-bvlc-master-cuda)) depend on the CPU version ([lib-caffe-bvlc-master-cpu](https://github.com/dividiti/ck-caffe/tree/master/package/lib-caffe-bvlc-master-cpu)).

**Comment by gfursin** [comment]
By the way, note, that I added an extra package with a new universal installer, but I keep the old one because we still didn't thoroughly check it ...
