### ISSUE TITLE
Add dependency on Fortran compiler to OpenBLAS 0.2.18+

### ISSUE THREAD

**Issue by psyhtest** [ctuning/ck-math#2]
Building OpenBLAS failed on a machine with only `gcc-6` and `g++-6` installed, but not `gfortran-6`. Interestingly, the machine had `gfortran-5` installed (aliased as `gfortran`) but OpenBLAS clearly wanted to use everything from the "GNU tools 6 series"... And so did CK, because the CK environment of the failed build had the following variables set:

```
CK_F90=gfortran-6
CK_F95=gfortran-6
CK_FC=gfortran-6
```

Installing `gfortran-6` solved the issue. However, it's clear that OpenBLAS has a dependency on a Fortran compiler (perhaps even specifically `gfortran`) which should be specified explicitly in the package's metadata. Unfortunately, no Fortan compiler description is available in CK yet, so this issue will have to be stalled until that's resolved.

**Comment by psyhtest** [comment]
Ha-ha, OpenBLAS "clearly wanted" `gfortran-6` because... CK clearly told it so in the `install.sh` script just before calling `make`:

```
export FC=${CK_FC}
```

So CK should have been a bit more careful when setting up the environment. I believe an explicit dependency on a Fortran compiler would override the default value of `CK_FC`. This is actually one of the CK strengths where we can gradually cover all important dependencies once they are discovered...

**Comment by gfursin** [comment]
Indeed, I detect C and then set C++ and fortran without really checking whether they exists - it was done for a quick prototyping (particularly, since I rarely use Fortran nowadays). I agree that we should try to separate them and add fortran entry (and possibly c++ entry) . I will check it out later. And yes, the idea of CK, is to quickly prototype things and then gradually improve them (including meta and API), without breaking previous experiments!

**Comment by psyhtest** [comment]
Following @gfursin's resoluton of the corresponding `ctuning/ck-env` issue, I've added an explicit dependency on `gfortran`. I tried using the `lang-f95` tag but unfortunately the same was present in GCC (GNU C compiler), so I reverted to using the `gfortran` tag.

An open question whether a different Fortran compiler be used to compile OpenBLAS?

**Comment by gfursin** [comment]
I removed lang-f95 (and other fortran) tags from gcc soft description. However, you may need to reregister GCC env otherwise old tags will still be used. I also added tags "fortran". The same tag I added to compiler.icc (Intel compilers which include C and Fortran). If you use CK_FC env, you can compile your program with different fortran compilers, but I don't know about OpenBLAS ...

**Comment by psyhtest** [comment]
So now the `lib-openblas-0.2.19` package has the following dependencies:
```
  "deps": {
    "boost": {
      "local": "yes",
      "name": "Boost C++ libraries",
      "sort": 5,
      "tags": "lib,boost"
    },
    "c-compiler": {
      "add_to_path": "yes",
      "local": "yes",
      "name": "C compiler",
      "sort": 10,
      "tags": "compiler,lang-c"
    },
    "gfortran-compiler": {
      "add_to_path": "yes",
      "local": "yes",
      "name": "GNU Fortran compiler",
      "sort": 15,
      "tags": "compiler,gfortran",
      "only_for_target_os_tags": [
        "linux","windows"
      ]
    }
```

But its generalisation to non-Linux systems,  `lib-openblas-0.2.19-universal`, has the following ones:
```
  "deps": {
    "compiler": {
      "local": "yes",
      "name": "C compiler",
      "skip_from_bat":"yes",
      "only_for_target_os_tags": [
        "android",
        "linux"
      ],
      "sort": 10,
      "tags": "compiler,lang-c"
    },
    "utils-unix-win": {
      "local": "yes",
      "force_target_as_host": "yes",
      "name": "Unix Utils for Windows",
      "skip_from_bat":"yes",
      "only_for_host_os_tags": [
        "windows"
      ],
      "sort": 1,
      "tags": "utils,unix-win"
    },
    "compiler-perl": {
      "local": "yes",
      "force_target_as_host": "yes",
      "name": "Perl",
      "skip_from_bat":"yes",
      "only_for_host_os_tags": [
        "windows"
      ],
      "sort": 3,
      "tags": "compiler,perl"
    },
    "compiler-mingw": {
      "local": "yes",
      "force_target_as_host": "yes",
      "add_to_path":"yes",
      "name": "C compiler",
      "skip_from_bat":"yes",
      "only_for_host_os_tags": [
        "windows"
      ],
      "sort": 5,
      "tags": "compiler,lang-c,gcc"
    }
```
So the universal package is missing the Fortran dependency, as well as the Boost one (although it has a bunch of Windows-related ones). Should they be introduced?

**Comment by gfursin** [comment]
Boost doesn't seem to be needed, that's why I removed it (and it seemed to work fine since then for all targets). As for gfortran - yes, will try it now ...

**Comment by gfursin** [comment]
Added gfortran dependency for Linux and Windows to this package; did not add Boost because it's not needed; fixed gfortran detection in ck-env. Everything seems to be working so I am closing this ticket ...
