### ISSUE TITLE
Two suggestion

### ISSUE THREAD

**Issue by bhack** [ctuning/ck-math#6]
What do you think of:
https://github.com/hfp/libxsmm
https://github.com/01org/mkl-dnn

**Comment by gfursin** [comment]
Cool! Thanks for the suggestion - should be interesting! We will check/add it when we have resources. The more important thing is still to unify installation and testing of a current subset of libs for Caffe (CLBlas, CLBlast,libDNN, ISAAC, etc) ...

**Comment by psyhtest** [comment]
We now support building Caffe with MKL-DNN. (Part of [conversion](https://github.com/ctuning/ck-request-asplos18-caffe-intel) of [Intel's submission](https://github.com/intel/caffe/wiki/ReQuEST-Artifact-Installation-Guide) to [ReQuEST](http://cknowledge.org/request-cfp-asplos2018.html)).
